<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/29 0029
 * Time: 12:53
 */

namespace Home\Controller;


class KaiController extends HomeController
{
    protected $url_config = [  //type => url
        '43' =>[
            'url' =>  'http://cgi.im.qq.com/cgi-bin/minute_city', // 腾讯分分彩
            'dataFun' => 'getTXffc'
        ]
    ];
    protected $type = 0;

    public function _initialize()
    {
//        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function queryKJData()
    {
        $type = I('type');
        //查询开奖区号相关
        $this->type = $type;
        $fun = $this->url_config[$type]['dataFun'];
        $data = $this->$fun();
        $this->ajaxReturn($data,'JSON');
    }


    public function curlData($url="",$header="") {
        $postUrl = $url;
        $ch = curl_init();                                      //初始化curl
        curl_setopt($ch, CURLOPT_URL,$postUrl);                 //抓取指定网页
        curl_setopt($ch, CURLOPT_HEADER, 0);                    //设置header
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);            //要求结果为字符串且输出到屏幕上
        curl_setopt($ch, CURLOPT_HTTPHEADER,$header);           // 增加 HTTP Header（头）里的字段
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);        // 终止从服务端进行验证
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
        $data = curl_exec($ch);                                 //运行curl
        curl_close($ch);
        return $data;
    }

    /**
     * 腾讯分分彩
     * @return int
     */
    protected function getTXffc(){
        $url = $this->url_config[$this->type]['url'];
        $data = $this->curlData($url);
        $data = json_decode($data,true);
        $lastNo=$this->getGameLastNo($this->type,time());

        $newData['time'] = time();
        $newData['number'] = $lastNo['actionNo'];
        $kjnum = end($data['minute']);
        $kjnum = substr($kjnum,-4);
        //第二个数
        $num2 = substr($kjnum,0,1);
        //第三个数
        $num3 = substr($kjnum,1,1);
        //第四个数
        $num4 = substr($kjnum,2,1);
        //第五个数
        $num5 = substr($kjnum,3,1);
        // 第一个数
        $num1 = substr($num2+$num3+$num4+$num5,-1);
        $newData['data'] = $num1.','.$num2.','.$num3.','.$num4.','.$num5;
        return $newData;
    }

    public function getQQData()
    {
        $url = 'http://77tj.org/api/tencent/onlineim';
        $data = $this->curlData($url);
        $data = json_decode($data,true)[0];
        $newData['time'] = strtotime($data['onlinetime']);
        $newData['datetime'] = $data['onlinetime'];
        $actionNo = date('H', strtotime($data['onlinetime']))*60 + date('i', strtotime($data['onlinetime']));
        $newData['number'] = date('Ymd-', strtotime($data['onlinetime'])) . substr(10000 + $actionNo, 1);
        $newData['base_number'] = $data['onlinenumber'];
        $kjnum = $data['onlinenumber'];

        $sum = 0;
        for($i=0;$i< strlen($kjnum); $i++){
            $sum = $sum + substr($kjnum,$i,1);
        }
        $num1 = substr($sum,-1);
        $kjnum = substr($kjnum,-4);
        //第二个数
        $num2 = substr($kjnum,0,1);
        //第三个数
        $num3 = substr($kjnum,1,1);
        //第四个数
        $num4 = substr($kjnum,2,1);
        //第五个数
        $num5 = substr($kjnum,3,1);
        // 第一个数
        $newData['data'] = $num1.','.$num2.','.$num3.','.$num4.','.$num5;
//        return json($newData);
        $this->ajaxReturn($newData,'JSON');
    }

    /**
     *
     *tx-ssc
     */
    public function gettxssc()
    {
         $url = 'http://tx-ssc.com/api/getData';
        $data = $this->curlData($url);
        $data = json_decode($data,true)[0];
        $newData['time'] = substr($data['time'], 0,10);
        $newData['datetime'] = date('Y-m-d H:i:s',$newData['time']);
        $actionNo = date('H', $newData['time'])*60 + date('i', $newData['time']);
        $newData['number'] = date('Ymd-', $newData['time']) . substr(10000 + $actionNo, 1);
        $newData['base_number'] = $data['code1'];
        $newData['code'] = $data['code'];
        $kjnum = $data['code1'];

        $sum = 0;
        for($i=0;$i< strlen($kjnum); $i++){
            $sum = $sum + substr($kjnum,$i,1);
        }
        $num1 = substr($sum,-1);
        $kjnum = substr($kjnum,-4);
        //第二个数
        $num2 = substr($kjnum,0,1);
        //第三个数
        $num3 = substr($kjnum,1,1);
        //第四个数
        $num4 = substr($kjnum,2,1);
        //第五个数
        $num5 = substr($kjnum,3,1);
        // 第一个数
        $newData['data'] = $num1.','.$num2.','.$num3.','.$num4.','.$num5;
        $this->ajaxReturn($newData,'JSON');
    }
    public function gethjqq(){
        $url = 'http://tpppay.cn/gettxssc';
        $data = $this->curlData($url);
        $this->ajaxReturn(json_decode($data),'JSON');
    }
}